Repository BitcreditProtocol/Wildcat, pull requests merged in 2025-04, with the labels that each got.

#99 [bcr-wdc-quote-service] fix openapi definitions
  crates/bcr-wdc-quote-service/src/admin.rs
  crates/bcr-wdc-quote-service/src/lib.rs
  crates/bcr-wdc-quote-service/src/web.rs
Labels: enhancement, Review effort 2/5

#101 [openapi] fix docs for list quotes
  crates/bcr-wdc-quote-service/src/admin.rs
  crates/bcr-wdc-quote-service/src/lib.rs
  crates/bcr-wdc-webapi/src/quotes.rs
Labels: documentation, Review effort 2/5

#93 [workspace] upgrade to cdk 0.9
  Cargo.toml
  crates/bcr-wdc-bff-wallet-service/Cargo.toml
  crates/bcr-wdc-bff-wallet-service/src/lib.rs
  crates/bcr-wdc-bff-wallet-service/src/service.rs
  crates/bcr-wdc-bff-wallet-service/src/web.rs
  crates/bcr-wdc-ebpp/src/lib.rs
  crates/bcr-wdc-key-client/Cargo.toml
  crates/bcr-wdc-key-service/Cargo.toml
  crates/bcr-wdc-key-service/src/lib.rs
  crates/bcr-wdc-keys/Cargo.toml
  crates/bcr-wdc-keys/src/lib.rs
  crates/bcr-wdc-quote-service/Cargo.toml
  crates/bcr-wdc-quote-service/src/admin.rs
  crates/bcr-wdc-quote-service/src/lib.rs
  crates/bcr-wdc-quote-service/src/web.rs
  crates/bcr-wdc-swap-client/Cargo.toml
  crates/bcr-wdc-swap-client/src/lib.rs
  crates/bcr-wdc-swap-service/Cargo.toml
  crates/bcr-wdc-swap-service/src/lib.rs
  crates/bcr-wdc-swap-service/src/web.rs
  crates/bcr-wdc-treasury-client/Cargo.toml
  crates/bcr-wdc-treasury-service/Cargo.toml
  crates/bcr-wdc-webapi/Cargo.toml
  crates/bcr-wdc-webapi/src/wallet.rs
  docker/ebpp/config.toml
  recipe.json
Labels: enhancement, Review effort 2/5

#108 chore(wallet-bff): allow cors headers
  crates/bcr-wdc-bff-wallet-service/src/lib.rs
Labels: bug

#109 [bcr-wdc-ebpp] minor fixes
  crates/bcr-wdc-ebpp/Cargo.toml
  crates/bcr-wdc-ebpp/src/service.rs
Labels: bug

#115 [bcr-wdc-ebpp] refactor error and bdk_wallet Syncer
  crates/bcr-wdc-ebpp/Cargo.toml
  crates/bcr-wdc-ebpp/src/error.rs
  crates/bcr-wdc-ebpp/src/lib.rs
  crates/bcr-wdc-ebpp/src/onchain.rs
Labels: enhancement

#116 [workspace] remove unused dependencies
  crates/bcr-wdc-ebpp/Cargo.toml
  crates/bcr-wdc-keys/Cargo.toml
  crates/bcr-wdc-keys/src/lib.rs
  crates/bcr-wdc-keys/src/persistence.rs
  crates/bcr-wdc-quote-service/Cargo.toml
Labels: enhancement

#118 [bcr-wdc-ebpp] improve payment notification system
  crates/bcr-wdc-ebpp/src/lib.rs
  crates/bcr-wdc-ebpp/src/onchain.rs
  crates/bcr-wdc-ebpp/src/payment.rs
  crates/bcr-wdc-ebpp/src/persistence/inmemory.rs
  crates/bcr-wdc-ebpp/src/persistence/surreal.rs
  crates/bcr-wdc-ebpp/src/service.rs
  docker/ebpp/config.toml
Labels: enhancement

#119 [bcr-wdc-ebpp] implement APIs to make payments
  Cargo.toml
  crates/bcr-wdc-ebpp/Cargo.toml
  crates/bcr-wdc-ebpp/src/ebill.rs
  crates/bcr-wdc-ebpp/src/error.rs
  crates/bcr-wdc-ebpp/src/lib.rs
  crates/bcr-wdc-ebpp/src/onchain.rs
  crates/bcr-wdc-ebpp/src/payment.rs
  crates/bcr-wdc-ebpp/src/persistence/inmemory.rs
  crates/bcr-wdc-ebpp/src/persistence/surreal.rs
  crates/bcr-wdc-ebpp/src/service.rs
  docker/ebpp/config.toml
  docker/electrs/config.toml
  recipe.json
Labels: enhancement
