Repository BitcreditProtocol/Wildcat, pull requests merged in 2025-09, with the labels that each got.

#289 [dependencies] upgrade bcr-ebill-core to v0.4.5
  Cargo.toml
  crates/bcr-wdc-ebill-service/src/error.rs
  crates/bcr-wdc-ebill-service/src/lib.rs
  crates/bcr-wdc-ebill-service/src/main.rs
  crates/bcr-wdc-ebill-service/src/web.rs
  crates/bcr-wdc-ebpp/Cargo.toml
  crates/bcr-wdc-ebpp/src/persistence/inmemory.rs
  crates/bcr-wdc-ebpp/src/service.rs
  crates/bcr-wdc-quote-service/src/persistence/inmemory.rs
  crates/bcr-wdc-swap-service/src/persistence/inmemory.rs
  crates/bcr-wdc-treasury-service/src/persistence/inmemory.rs
  crates/bcr-wdc-webapi/src/bill.rs
  docker/ebill-service/config.toml
Labels: enhancement, Review effort 3/5

#288 CI Cache fix
  .github/workflows/test.yml
Labels: Review effort 1/5

#291 [docker]: upgrade rustc version
  docker/base-image/Dockerfile
Labels: bug, Review effort 1/5

#293 Add new dev relay
  docker/ebill-service/config.toml
Labels: Review effort 1/5
