Repository BitcreditProtocol/Wildcat, pull requests merged in 2025-05, with the labels that each got.

#124 NFC: [bcr-wdc-utils] change crate name
  Cargo.toml
  crates/bcr-wdc-key-client/Cargo.toml
  crates/bcr-wdc-key-client/src/lib.rs
  crates/bcr-wdc-key-client/tests/keys.rs
  crates/bcr-wdc-key-client/tests/keyset_info.rs
  crates/bcr-wdc-key-client/tests/pre_sign.rs
  crates/bcr-wdc-key-service/Cargo.toml
  crates/bcr-wdc-key-service/src/error.rs
  crates/bcr-wdc-key-service/src/factory.rs
  crates/bcr-wdc-key-service/src/persistence/inmemory.rs
  crates/bcr-wdc-key-service/src/persistence/surreal.rs
  crates/bcr-wdc-key-service/src/service.rs
  crates/bcr-wdc-quote-service/Cargo.toml
  crates/bcr-wdc-quote-service/src/error.rs
  crates/bcr-wdc-quote-service/src/keys.rs
  crates/bcr-wdc-quote-service/src/service.rs
  crates/bcr-wdc-quote-service/src/utils.rs
  crates/bcr-wdc-quote-service/src/wallet.rs
  crates/bcr-wdc-quote-service/src/web.rs
  crates/bcr-wdc-swap-client/Cargo.toml
  crates/bcr-wdc-swap-client/tests/swap.rs
  crates/bcr-wdc-swap-service/Cargo.toml
  crates/bcr-wdc-swap-service/src/lib.rs
  crates/bcr-wdc-swap-service/src/persistence/surreal.rs
  crates/bcr-wdc-swap-service/src/service.rs
  crates/bcr-wdc-swap-service/src/utils.rs
  crates/bcr-wdc-treasury-service/Cargo.toml
  crates/bcr-wdc-treasury-service/src/credit/mod.rs
  crates/bcr-wdc-treasury-service/src/debit/service.rs
  crates/bcr-wdc-treasury-service/src/error.rs
  crates/bcr-wdc-treasury-service/src/persistence/surreal.rs
  crates/bcr-wdc-utils/Cargo.toml
  crates/bcr-wdc-utils/src/id.rs
  crates/bcr-wdc-utils/src/keys.rs
  crates/bcr-wdc-utils/src/lib.rs
  crates/bcr-wdc-webapi/Cargo.toml
  crates/bcr-wdc-webapi/src/bin/devtool.rs
Labels: enhancement

#129 [docker] Add platform amd64 for cdk_mint in compose
  docker-compose.yml
Labels: Review effort 1/5

#135 [bcr-wdc-swap-client] Test P2PK verification on swap service
  crates/bcr-wdc-swap-client/tests/swap.rs
Labels: Review effort 2/5

#133 [workspace] introduce cargo-deny
  Cargo.toml
  crates/bcr-wdc-ebpp/Cargo.toml
  crates/bcr-wdc-key-client/Cargo.toml
  crates/bcr-wdc-key-service/Cargo.toml
  crates/bcr-wdc-quote-service/Cargo.toml
  crates/bcr-wdc-swap-client/Cargo.toml
  crates/bcr-wdc-swap-service/Cargo.toml
  crates/bcr-wdc-treasury-client/Cargo.toml
  crates/bcr-wdc-treasury-service/Cargo.toml
  crates/bcr-wdc-utils/Cargo.toml
  crates/bcr-wdc-wallet-aggregator/Cargo.toml
  crates/bcr-wdc-webapi/Cargo.toml
  deny.toml
Labels: enhancement

#139 fix cargo chef recipe.json
  recipe.json
Labels: bug

#151 [bcr-wdc-e2e-tests] Build e2e on master branch and use read permissions
  .github/workflows/e2e-test.yml
Labels: bug, Review effort 1/5

#150 [bcr-wdc-ebpp] implement treasury request_to_mint signature verification
  crates/bcr-wdc-ebpp/Cargo.toml
  crates/bcr-wdc-ebpp/src/error.rs
  crates/bcr-wdc-ebpp/src/lib.rs
  crates/bcr-wdc-ebpp/src/service.rs
Labels: bug

#153 [bcr-wdc-ebpp] small refactor + more tests
  crates/bcr-wdc-ebpp/src/service.rs
Labels: enhancement

#156 [bcr-wdc-e2e-tests] fix strum version
  Cargo.toml
  recipe.json
Labels: enhancement

#159 [bcr-wdc-ebpp] Add example treasury service public key
  docker/ebpp/config.toml
Labels: Review effort 1/5

#158 [bcr-wdc-wallet-aggregator] determine swap type
  crates/bcr-wdc-wallet-aggregator/Cargo.toml
  crates/bcr-wdc-wallet-aggregator/src/web.rs
Labels: enhancement

#164 [bcr-wdc-wallet-aggregator] add /v1/restore API
  crates/bcr-wdc-wallet-aggregator/src/web.rs
Labels: enhancement

#172 [bcr-wdc-key-service] fix issue with surrealdb in storing signatures
  crates/bcr-wdc-key-service/src/persistence/surreal.rs
Labels: bug

#168 ci: build & push images to GAR with base image caching
  .github/workflows/build.yml
Labels: enhancement, devtools

#175 feat(docker): parameterize base image via ARG WILDCAT_BASE_IMAGE
  docker/ebill-service/Dockerfile
  docker/ebpp/Dockerfile
  docker/key-service/Dockerfile
  docker/quote-service/Dockerfile
  docker/swap-service/Dockerfile
  docker/treasury-service/Dockerfile
  docker/wallet-aggregator/Dockerfile
Labels: enhancement

#176 Don't store signature twice
  crates/bcr-wdc-key-service/src/service.rs
Labels: bug

#171 [bcr-wdc-ebpp] implement EBillClient
  crates/bcr-wdc-ebpp/Cargo.toml
  crates/bcr-wdc-ebpp/src/ebill.rs
  crates/bcr-wdc-ebpp/src/error.rs
  crates/bcr-wdc-ebpp/src/lib.rs
Labels: enhancement
