Repository BitcreditProtocol/Wildcat, pull requests merged in 2025-03, with the labels that each got.

#62 ci: Update branch wildcard to trigger actions on branches with slashes
  .github/workflows/rust.yml
  .github/workflows/test.yml
Labels: Review effort 1/5

#65 [bcr-wdc-keys] add verify_with_keys
  crates/bcr-wdc-keys/src/lib.rs
  crates/bcr-wdc-quote-service/src/error.rs
  crates/bcr-wdc-swap-service/src/utils.rs
Labels: enhancement, Review effort 2/5

#67 [bcr-wdc-webapi] add IdentityPublicData
  crates/bcr-wdc-quote-service/src/lib.rs
  crates/bcr-wdc-quote-service/src/quotes.rs
  crates/bcr-wdc-webapi/src/quotes.rs
Labels: enhancement, Review effort 2/5

#68 add dockerfiles and configs for services
  crates/bcr-wdc-key-service/src/lib.rs
  crates/bcr-wdc-key-service/src/main.rs
  crates/bcr-wdc-quote-service/src/main.rs
  crates/bcr-wdc-swap-service/src/main.rs
  docker-compose.yml
  docker/key-service/Dockerfile
  docker/key-service/config.toml
  docker/quote-service/config.toml
  docker/swap-service/Dockerfile
  docker/swap-service/config.toml
  wildcat.toml
Labels: enhancement, Review effort 2/5

#89 chore: add cdk mint to docker compose setup
  docker-compose.yml
Labels: Review effort 2/5, devtools

#90 chore(build): cargo fmt
  crates/bcr-wdc-key-service/src/lib.rs
  crates/bcr-wdc-key-service/src/main.rs
  crates/bcr-wdc-quote-service/src/main.rs
  crates/bcr-wdc-swap-service/src/lib.rs
  crates/bcr-wdc-swap-service/src/main.rs
  crates/bcr-wdc-treasury-service/src/main.rs
Labels: Review effort 1/5

#88 code-coverage: cover full workspace
  .github/workflows/test.yml
Labels: enhancement, Review effort 2/5

#94 [docker] refactor docker files
  docker-compose.yml
  docker/base-image/Dockerfile
  docker/cdk-mintd/config.toml
  docker/key-service/Dockerfile
  docker/key-service/config.toml
  docker/quote-service/Dockerfile
  docker/swap-service/Dockerfile
  docker/swap-service/config.toml
  docker/treasury-service/Dockerfile
  docker/treasury-service/config.toml
  justfile
  recipe.json
Labels: enhancement, Review effort 2/5

#91 dev: user wallet bff skeleton
  .github/workflows/rust.yml
  Cargo.toml
  crates/bcr-wdc-bff-wallet-service/Cargo.toml
  crates/bcr-wdc-bff-wallet-service/example.config.toml
  crates/bcr-wdc-bff-wallet-service/src/error.rs
  crates/bcr-wdc-bff-wallet-service/src/lib.rs
  crates/bcr-wdc-bff-wallet-service/src/main.rs
  crates/bcr-wdc-bff-wallet-service/src/service.rs
  crates/bcr-wdc-bff-wallet-service/src/web.rs
  docker-compose.yml
  docker/bff-wallet-service/Dockerfile
  docker/bff-wallet-service/config.toml
  justfile
Labels: Review effort 2/5

#95 chore(bff-wallet): add cors headers
  crates/bcr-wdc-bff-wallet-service/Cargo.toml
  crates/bcr-wdc-bff-wallet-service/src/lib.rs
Labels: Review effort 1/5
