Repository BitcreditProtocol/Wildcat, pull requests merged in 2025-06, with the labels that each got.

#210 Add checkstate and keyset info to Wallet Aggregator Service
  crates/bcr-wdc-wallet-aggregator/src/lib.rs
  crates/bcr-wdc-wallet-aggregator/src/web.rs
  docker/bff-wallet-service/nginx.conf
Labels: Review effort 2/5

#218 treasury and ebpp admin endpoint URIs
  crates/bcr-wdc-ebpp-client/src/lib.rs
  crates/bcr-wdc-ebpp/src/admin.rs
  crates/bcr-wdc-ebpp/src/lib.rs
  crates/bcr-wdc-treasury-client/src/lib.rs
  crates/bcr-wdc-treasury-service/Cargo.toml
  crates/bcr-wdc-treasury-service/src/admin.rs
  crates/bcr-wdc-treasury-service/src/lib.rs
  docker/bff-dashboard-service/envoy.yaml
Labels: enhancement, Review effort 3/5

#219 [bcr-wdc-ebpp] fix docker config
  docker/ebpp/config.toml
Labels: bug, Review effort 2/5

#223 Download and decrypt req to mint file Endpoint
  crates/bcr-wdc-ebill-client/src/lib.rs
  crates/bcr-wdc-ebill-client/tests/contact.rs
  crates/bcr-wdc-ebill-service/Cargo.toml
  crates/bcr-wdc-ebill-service/src/error.rs
  crates/bcr-wdc-ebill-service/src/lib.rs
  crates/bcr-wdc-ebill-service/src/web.rs
  crates/bcr-wdc-webapi/src/contact.rs
  crates/bcr-wdc-webapi/src/quotes.rs
  docker/bff-dashboard-service/envoy.yaml
Labels: Review effort 4/5

#233 Up ebill to 0.3.16
  Cargo.toml
  crates/bcr-wdc-ebill-service/Cargo.toml
  crates/bcr-wdc-ebill-service/src/error.rs
  crates/bcr-wdc-ebill-service/src/lib.rs
  crates/bcr-wdc-ebill-service/src/main.rs
Labels: Review effort 2/5

#236 [bcr-wdc-ebpp] fix spawn_blocking calls
  crates/bcr-wdc-ebpp/src/onchain.rs
Labels: bug, Review effort 2/5

#235 [bcr-wdc-ebill-client] BillCombinedBitcoinKey fix
  crates/bcr-wdc-ebill-client/Cargo.toml
  crates/bcr-wdc-ebill-client/src/lib.rs
  crates/bcr-wdc-ebill-client/tests/bills.rs
  crates/bcr-wdc-ebpp/src/ebill.rs
  crates/bcr-wdc-ebpp/src/error.rs
  crates/bcr-wdc-webapi/src/bill.rs
Labels: bug, Review effort 2/5

#241 [e2e] fix config issues
  docker-compose-e2e.yml
  docker/treasury-service/config.toml
  docker/wallet-aggregator/config.toml
Labels: bug, Review effort 2/5

#238 Use node id and bill id, up ebill
  Cargo.toml
  crates/bcr-wdc-e2e-tests/src/main.rs
  crates/bcr-wdc-ebill-client/src/lib.rs
  crates/bcr-wdc-ebill-client/tests/bills.rs
  crates/bcr-wdc-ebill-service/Cargo.toml
  crates/bcr-wdc-ebill-service/src/lib.rs
  crates/bcr-wdc-ebill-service/src/main.rs
  crates/bcr-wdc-ebill-service/src/web.rs
  crates/bcr-wdc-ebpp/src/ebill.rs
  crates/bcr-wdc-ebpp/src/service.rs
  crates/bcr-wdc-quote-client/Cargo.toml
  crates/bcr-wdc-quote-client/tests/enquire.rs
  crates/bcr-wdc-quote-service/Cargo.toml
  crates/bcr-wdc-quote-service/src/persistence/inmemory.rs
  crates/bcr-wdc-quote-service/src/persistence/surreal.rs
  crates/bcr-wdc-quote-service/src/quotes.rs
  crates/bcr-wdc-quote-service/src/service.rs
  crates/bcr-wdc-quote-service/src/web.rs
  crates/bcr-wdc-treasury-service/src/debit/service.rs
  crates/bcr-wdc-treasury-service/src/debit/wildcat.rs
  crates/bcr-wdc-webapi/src/bill.rs
  crates/bcr-wdc-webapi/src/identity.rs
  crates/bcr-wdc-webapi/src/quotes.rs
  crates/bcr-wdc-webapi/src/signatures.rs
  crates/bcr-wdc-webapi/src/test_utils.rs
  docker/ebill-service/config.toml
Labels: Review effort 4/5
