Repository BitcreditProtocol/Wildcat, pull requests merged in 2025-07, with the labels that each got.

#253 [bff-dashboard-service] Expose identity detail endpoint
  docker/bff-dashboard-service/envoy.yaml
Labels: enhancement, Review effort 2/5

#262 ci: update deploy-dev workflow
  .env.template
  .github/workflows/deploy-dev.yml
  common-services.yml
  deployment-configuration-local.yml
  deployment-configuration.yml
Labels: Review effort 3/5, Possible security concern

#267 ci: add deploy.yml (env: production / wildcat-docker)
  .github/workflows/deploy.yml
Labels: Review effort 4/5, Possible security concern

#269 change to version 0.4.0
  Cargo.toml
Labels: Review effort 1/5

#260 Put full shared bill in enquire payload
  CHANGELOG.md
  Cargo.toml
  crates/bcr-wdc-e2e-tests/Cargo.toml
  crates/bcr-wdc-e2e-tests/src/main.rs
  crates/bcr-wdc-e2e-tests/src/test_utils.rs
  crates/bcr-wdc-ebill-client/Cargo.toml
  crates/bcr-wdc-ebill-client/src/lib.rs
  crates/bcr-wdc-ebill-client/tests/bills.rs
  crates/bcr-wdc-ebill-service/Cargo.toml
  crates/bcr-wdc-ebill-service/src/error.rs
  crates/bcr-wdc-ebill-service/src/lib.rs
  crates/bcr-wdc-ebill-service/src/web.rs
  crates/bcr-wdc-ebpp/Cargo.toml
  crates/bcr-wdc-quote-client/src/lib.rs
  crates/bcr-wdc-quote-client/tests/enquire.rs
  crates/bcr-wdc-quote-client/tests/list.rs
  crates/bcr-wdc-quote-client/tests/lookup.rs
  crates/bcr-wdc-quote-service/Cargo.toml
  crates/bcr-wdc-quote-service/src/admin.rs
  crates/bcr-wdc-quote-service/src/ebill.rs
  crates/bcr-wdc-quote-service/src/error.rs
  crates/bcr-wdc-quote-service/src/lib.rs
  crates/bcr-wdc-quote-service/src/persistence/surreal.rs
  crates/bcr-wdc-quote-service/src/quotes.rs
  crates/bcr-wdc-quote-service/src/service.rs
  crates/bcr-wdc-quote-service/src/web.rs
  crates/bcr-wdc-webapi/src/bin/devtool.rs
  crates/bcr-wdc-webapi/src/quotes.rs
  crates/bcr-wdc-webapi/src/test_utils.rs
  docker/quote-service/config.toml
Labels: Review effort 4/5, Possible security concern

#272 ci: change dev deployment workflow
  .github/workflows/deploy-dev.yml
  .github/workflows/nightly.yml
Labels: Review effort 3/5

#276 [bcr-wdc-wallet-aggregator] minor fix in info
  crates/bcr-wdc-wallet-aggregator/src/web.rs
Labels: bug, Review effort 1/5
